{% set version = "0.36.2" %}

package:
  name: referencing
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/referencing/referencing-{{ version }}.tar.gz
  sha256: df2e89862cd09deabbdba16944cc3f10feb6b3e6f18e902f7cc25609a34775aa

build:
  noarch: python
  number: 0
  script_env:
    - REFERENCING_SUITE=./suite
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - attrs >=22.2.0
    - python >={{ python_min }}
    - rpds-py >=0.7.0
    - typing_extensions >=4.4.0

test:
  source_files:
    - suite
  imports:
    - referencing
  commands:
    - pip check
    - pytest -vv --pyargs referencing --cov=referencing --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=99
  requires:
    - pip
    - pytest-cov
    - pytest-subtests
    - python {{ python_min }}

about:
  home: https://github.com/python-jsonschema/referencing
  summary: JSON Referencing + Python
  license: MIT
  license_file: COPYING
  doc_url: https://referencing.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
